version: '3.8'

services:
  web:
    image: olegreznik/tree-structure-api:latest
    container_name: tree-structure-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__TreeStructure=${DB_CONNECTION_STRING}
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: tree-structure-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: